### ISSUE TITLE
有个尴尬的小问题

### ISSUE THREAD

**Issue by TobiahShaw** [yewei02538/HiPermission#17]
如果在去设置之后，打开应用设置，这是不去打开权限而是去关闭权限（关闭任一）再返回就会造成activity退出

**Comment by TobiahShaw** [comment]
java.lang.RuntimeException: Unable to resume activity {com.xxx.xxx/me.weyye.hipermission.PermissionActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=110, result=0, data=null} to activity {com.xxx.xxx/me.weyye.hipermission.PermissionActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.ListIterator java.util.List.listIterator()' on a null object reference
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3176)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3207)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2544)
	at android.app.ActivityThread.access$900(ActivityThread.java:168)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1378)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:150)
	at android.app.ActivityThread.main(ActivityThread.java:5665)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:822)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:712)
Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=110, result=0, data=null} to activity {com.xxx.xxx/me.weyye.hipermission.PermissionActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.ListIterator java.util.List.listIterator()' on a null object reference
	at android.app.ActivityThread.deliverResults(ActivityThread.java:3778)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3163)
	... 10 more
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.ListIterator java.util.List.listIterator()' on a null object reference
	at me.weyye.hipermission.PermissionActivity.checkPermission(PermissionActivity.java:298)
	at me.weyye.hipermission.PermissionActivity.onActivityResult(PermissionActivity.java:285)
	at android.app.Activity.dispatchActivityResult(Activity.java:6602)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:3774)
	... 11 more
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=110, result=0, data=null} to activity {com.xxx.xxx/me.weyye.hipermission.PermissionActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.ListIterator java.util.List.listIterator()' on a null object reference
	at android.app.ActivityThread.deliverResults(ActivityThread.java:3778)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3163)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3207)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2544)
	at android.app.ActivityThread.access$900(ActivityThread.java:168)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1378)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:150)
	at android.app.ActivityThread.main(ActivityThread.java:5665)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:822)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:712)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.ListIterator java.util.List.listIterator()' on a null object reference
	at me.weyye.hipermission.PermissionActivity.checkPermission(PermissionActivity.java:298)
	at me.weyye.hipermission.PermissionActivity.onActivityResult(PermissionActivity.java:285)
	at android.app.Activity.dispatchActivityResult(Activity.java:6602)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:3774)
	... 11 more
java.lang.NullPointerException: Attempt to invoke interface method 'java.util.ListIterator java.util.List.listIterator()' on a null object reference
	at me.weyye.hipermission.PermissionActivity.checkPermission(PermissionActivity.java:298)
	at me.weyye.hipermission.PermissionActivity.onActivityResult(PermissionActivity.java:285)
	at android.app.Activity.dispatchActivityResult(Activity.java:6602)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:3774)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3163)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3207)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2544)
	at android.app.ActivityThread.access$900(ActivityThread.java:168)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1378)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:150)
	at android.app.ActivityThread.main(ActivityThread.java:5665)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:822)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:712)

**Comment by HeMa321** [comment]
你解决了吗?还是换了另一个三方库

**Comment by TobiahShaw** [comment]
没有解决，我猜测可能和机制有关，我这边关闭权限的一瞬间进程就dead了，可能需要重启应用来确保权限关闭



发自我的小米手机
在 HeMa321 <notifications@github.com>，2018年1月30日 16:46写道：

你解决了吗?还是换了另一个三方库

**Comment by 880634** [comment]
可以看看这个，也很不错 https://github.com/getActivity/XXPermissions
