### ISSUE TITLE
android 8.0系统吊起权限就崩溃了

### ISSUE THREAD

**Issue by Cuiernao** [yewei02538/HiPermission#29]
` java.lang.RuntimeException: Unable to start activity ComponentInfo{com.njsoft.ace/me.weyye.hipermission.PermissionActivity}: java.lang.IllegalStateException: **Only fullscreen opaque activities can request orientation**
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)`

**Comment by msy801006** [comment]
感觉这个是Android的一个BUG只有8.0有这个问题，8.1以后的也没有这个问题

**Comment by JamesLiAndroid** [comment]
我也存在这个问题

**Comment by JunWeiAndroid** [comment]
找到 CustomTheme_Dialog  这个style，复制到你的styles里面，把透明背景去掉，或者改成非全透明背景，就可以了

**Comment by Hollz** [comment]
AndroidManifest.xml  文件中
设置activity 方向造成的，注释掉这行；@yewei02538
android:screenOrientation="portrait"
